name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1.4.0
      - name: Install Dependencies
        run: flutter packages get
      - name: Format
        run: flutter format --set-exit-if-changed lib test
      - name: Analyze
        run: flutter analyze --no-pub lib test
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          name: Codecov
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
